### PR TITLE
Add scaling support for 1 and 2 depth images

### PR DESCRIPTION
**Pull request by fire-eggs**
I don't have a lot of depth=1 images, but I have some. I haven't yet stumbled across any depth=2 files, so I grabbed from the interwebs.

The one part of the change I'm not happy with is the code for "use single channel": that doesn't make sense for 1 or 2 bytes-per-pixel images, because there IS only a single channel... But I left it in place.

Attached are samples of each type of image:

[1bpp_png.zip](https://github.com/rageworx/fl_imgtk/files/6524615/1bpp_png.zip)

[2bpp_png.zip](https://github.com/rageworx/fl_imgtk/files/6524612/2bpp_png.zip)

### CODE REVIEW

**Comment by rageworx** [comment]
Dear kevin,
Your PNGs are just Y-channel ( or gray 4 or 8bit depth ) images, and it meaning 1 depth.
Here some recognized information by using 'file' ( you will know what 'file' doing on POSIX )

image

And I think it should be converted by loading with Fl_PNG_Image(), or ...
Most of there's many different depths from PNG images, and it also converted to RGB for drawing image to modern display...
And there's problem, depth 1 should be wortk for 8bit grayscale, but 2 depth meaning of these : RGB555, RGB565, or 10 to 16bit grayscale ( you can refer to my medical image processing library, librawprocessor here, https://github.com/rageworx/librawprocessor, also need to understand window-width to compress color space ).
I think FLTK 1 depth meaning 1byte, and it is a single 8bit Grayscaled.
Also 2 depth is designed to sens as RGB555 or RGB565 ( mostly it used in old feature phones, Qualcomm brew graphics are designed to 16bit RGB color space for Red5, Green6, Blue5 ), and it means 2bytes.
So I think how about making adapter layer like Fl_RGB_Image* KevinToolKit::ConvertGray2RGB( your gray image up to 8bit ); ?

And tested your images, 1548229.png loads well, but tbbn1g04_depth2.png is loads as wrong image, maybe Fl_PNG_Image read image as wrong byte depth. I've tested my Super Resoultion Library ( libsrcnn here: https://github.com/rageworx/libsrcnn ) also read as wrong image.

image

It seems wrong implementation Fl_PNG_Image misleading to wrong image depth.
I will pending your pull request for next time ...

**Comment by rageworx** [comment]
plus, 
you can refer to librawprocessor, there's same resizing method for 16bit depth gray images ( mostly used for medical imaging, and DICOM tag ), or refer to super resolution imaging with colvolution neural network for Y channels only ( it meaning gray ).

**Comment by rageworx** [comment]
Dear Kevin,
I've tested your PNG images with own PNG-reading-test, and found an error reason,
See test result,

image

And source codes ( for MacOS llvm-g++ with Makefile ) here,
[pngtest1.zip](https://github.com/rageworx/fl_imgtk/files/6526337/pngtest1.zip)

And this problem belong to load_png_() of Fl_PNG_Image.cxx.
You 4bit image has transparency channel, and Fl_PNG_Image increases channel byte when match png_get_tRNS() returns transparency greater than zero ( line 173 of Fl_PNG_Imager, see here, https://github.com/rageworx/fltk-1.3.5-2-ts/blob/bf3a66aa87d57b8f4999040e05e504e99432e377/src/Fl_PNG_Image.cxx#L173 ) .
It must be calculated color channels and alpha channel separately.
I think it should be fixed as like, ( channel == 1 ) && ( alphachannel > 0 ) must be converted gray->RGB and muxed with alpha channel, because FLTK cannot handle grayscale with alpha channel.

How about your opinion ?
I will try fix it for my FLTK repository, and being test, then report to fltk/fltk main repo.
My repository was created than faster than fltk/fltk in github, so I couldn't forked them.

Regards, Raph.

**Comment by rageworx** [comment]
Dear Kevin,
Here I fixed own Fl_PNG_Image of FLTK-1.4.0-dev branch here,
https://github.com/rageworx/fltk-1.3.5-2-ts/commit/bde47a3c50860116fce31159ddb6dc83e4e54810

You can test it, and no error occurs, I will report to FLTK.

**Comment by fire-eggs** [comment]
Hi, Raph - My thanks for all this research! 

>I will pending your pull request for next time ...
Sure, I provided it just in case of interest. 1- and 2-bit-per-pixel images must be pretty rare these days!

I didn't have much luck with `file` or event imagemagick's `identify` commands. They wouldn't tell me the bit depth of anything. I will check out your other libraries: all sorts of new toys to play with !! ;-)

I should have mentioned the caveat that I was testing on Linux, and not using the system libpng. I'm using the the FLTK PNG code, but patched to support APNG. I'll take a look again at my code base and see where the differences are, perhaps the APNG patch fixes the issue? I'm certain you've found a bug in FLTK...

`tbbn1g04_depth2.png` is actually from the libpng resources site, so I've been operating on the assumption that it is valid. Another reason why I think you've found a legit bug in the vanilla FLTK code.

I can't dig into this until later today. I should also test on Windows, to see whether GDI handles these PNG files correctly.

Thanks again - I'm learning a bunch of stuff!
Kevin

**Comment by Albrecht-S** [comment]
> Attached are samples of each type of image:
1bpp_png.zip
2bpp_png.zip

@fire-eggs: FYI: I downloaded the posted zip files and extracted the images. `file` shows:
```
1548229.png:         PNG image data, 600 x 600, 8-bit grayscale, non-interlaced
tbbn1g04_depth2.png: PNG image data, 32 x 32, 4-bit grayscale, non-interlaced
```
The first image is **8-bit, no alpha**, the second image is **4-bit + alpha** (tested).

I can't see any _"1 or 2 bpp images"_.

And, BTW, these image load fine in FLTK.

**Comment by fire-eggs** [comment]
@Albrecht-S :
Drat! You caught me being sloppy again!  "bpp" does _not_ translate to "bytes per pixel". The terms I should have used were "depth1 and depth2".

Thank you for confirming the images load with FLTK. I'd not had any problem myself, but I'm using the FLTK PNG code (not the system libpng) patched for APNG support. I've not yet had a chance to personally re-test with "vanilla" FLTK-PNG or libpng.

Kevin

**Comment by Albrecht-S** [comment]
> Thank you, too, for mentioning the "depth2" images in the FLTK docs. I'd been struggling to find valid samples ...

FTR: When I **looked** at these images I couldn't find any evidence that the alpha channel was anything but opaque, but maybe it was in some parts I didn't notice. I don't know who created these images and how they were created.

**Comment by rageworx** [comment]
Ok Thanks for all, @fire-eggs  and @Albrecht-S  !
I was guessed 2 depths image may leading to RGB555 or RGB565 by converting in Fl_BMP_Image conversion ( https://github.com/fltk/fltk/blob/da4d16b59ab354e9c1fc944e814519bd8e251922/src/Fl_BMP_Image.cxx#L412 )
I will rollback to origin Fl_PNG_Image.cxx.

@fire-eggs , Do you continued this pull request for main ?
I will merge it if you want.

**Comment by fire-eggs** [comment]
>@fire-eggs , Do you continued this pull request for main ? I will merge it if you want.

I'm going to continue using this code in my project. Whether it makes sense for your usage, that's up to you.

**Comment by rageworx** [comment]
Dear @fire-eggs 
I've been merged and will be modify some codes for POSIX.
Regards, Raph.K.

**Pull request merged**
